Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/02/2023
Var
// Seção de Declarações das variáveis 
numero, i, resto: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   escreval(" DIGITE UM NUMERO: ")
   leia(numero)
   
   para i <- numero faca
        resto <- numero mod i
        se (resto=0


Fimalgoritmo