Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 14/02/2023
Var
// Seção de Declarações das variáveis 
n1, n2, n3 : inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva ("escreva o primeiro numero: ")
leia (n1)

escreva ("digite o segundo numero: ")
leia (n2)

escreva ("digite o terceiro numero: ")
leia (n3)



Fimalgoritmo