Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 14/02/2023
Var
// Seção de Declarações das variáveis 
Nome: Caractere
idade: Inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    Escreval ("Ecreva o nome: ")
    Leia (nome)
    
    Escreval ("Digite a idade: ")
    Leia (idade)
    
    Escreval (nome,idade)
    
    
Fimalgoritmo